-- ============================================================
-- PHASE 3: DATABASE HARDENING MIGRATION
-- NOC IT AI v3.0 — Production Grade
-- Applied: 2026-07-02
-- ============================================================

BEGIN;

-- ============================================================
-- 1. MISSING TABLES: retry_history
-- Tracks all retry attempts from DLQ worker
-- ============================================================
CREATE TABLE IF NOT EXISTS retry_history (
    id              BIGSERIAL PRIMARY KEY,
    dlq_id          INTEGER REFERENCES dlq_hybrid(dlq_id) ON DELETE CASCADE,
    attempt_number  INTEGER NOT NULL DEFAULT 1,
    attempted_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    success         BOOLEAN NOT NULL DEFAULT FALSE,
    error_reason    TEXT,
    response_code   TEXT,
    retry_strategy  TEXT DEFAULT 'exponential_backoff',
    site_id         TEXT DEFAULT 'global',
    event_id        TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_retry_history_dlq_id    ON retry_history(dlq_id);
CREATE INDEX IF NOT EXISTS idx_retry_history_site_id   ON retry_history(site_id);
CREATE INDEX IF NOT EXISTS idx_retry_history_event_id  ON retry_history(event_id);
CREATE INDEX IF NOT EXISTS idx_retry_history_attempted ON retry_history(attempted_at DESC);

COMMENT ON TABLE retry_history IS 'Full audit trail of DLQ retry attempts per event';

-- ============================================================
-- 2. MISSING TABLES: trace_integrity_reports
-- Generated by Phase 11 Trace Orphan Auditor
-- ============================================================
CREATE TABLE IF NOT EXISTS trace_integrity_reports (
    id                  BIGSERIAL PRIMARY KEY,
    report_type         TEXT NOT NULL, -- 'orphan_trace','missing_parent','broken_chain','incomplete_lineage'
    trace_id            TEXT,
    parent_trace_id     TEXT,
    event_id            TEXT,
    incident_id         INTEGER,
    site_id             TEXT DEFAULT 'global',
    severity            TEXT DEFAULT 'WARNING', -- WARNING, CRITICAL
    description         TEXT,
    detected_at         TIMESTAMP NOT NULL DEFAULT NOW(),
    resolved            BOOLEAN DEFAULT FALSE,
    resolved_at         TIMESTAMP,
    resolver            TEXT,
    scan_run_id         TEXT, -- groups reports from same scan run
    raw_data            JSONB DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_trace_reports_trace_id   ON trace_integrity_reports(trace_id);
CREATE INDEX IF NOT EXISTS idx_trace_reports_type       ON trace_integrity_reports(report_type);
CREATE INDEX IF NOT EXISTS idx_trace_reports_site       ON trace_integrity_reports(site_id);
CREATE INDEX IF NOT EXISTS idx_trace_reports_detected   ON trace_integrity_reports(detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_trace_reports_unresolved ON trace_integrity_reports(resolved) WHERE resolved = FALSE;

COMMENT ON TABLE trace_integrity_reports IS 'Audit reports from automated trace integrity scans (Phase 11)';

-- ============================================================
-- 3. MISSING TABLES: agent_trust_scores
-- Per-agent trust scoring for policy decisions (Phase 6)
-- ============================================================
CREATE TABLE IF NOT EXISTS agent_trust_scores (
    id                      BIGSERIAL PRIMARY KEY,
    agent_name              TEXT NOT NULL UNIQUE,
    site_id                 TEXT DEFAULT 'global',
    trust_score             NUMERIC(5,2) NOT NULL DEFAULT 100.0, -- 0.0 to 100.0
    heartbeat_score         NUMERIC(5,2) DEFAULT 100.0,
    false_positive_penalty  NUMERIC(5,2) DEFAULT 0.0,
    execution_success_bonus NUMERIC(5,2) DEFAULT 0.0,
    rollback_frequency_penalty NUMERIC(5,2) DEFAULT 0.0,
    telemetry_integrity_score  NUMERIC(5,2) DEFAULT 100.0,
    spoof_detection_flag    BOOLEAN DEFAULT FALSE,
    total_events_processed  INTEGER DEFAULT 0,
    total_false_positives   INTEGER DEFAULT 0,
    total_rollbacks         INTEGER DEFAULT 0,
    total_successes         INTEGER DEFAULT 0,
    last_seen_at            TIMESTAMP,
    last_scored_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    score_version           INTEGER DEFAULT 1,
    notes                   TEXT,
    created_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_trust_scores_agent    ON agent_trust_scores(agent_name);
CREATE INDEX IF NOT EXISTS idx_trust_scores_site     ON agent_trust_scores(site_id);
CREATE INDEX IF NOT EXISTS idx_trust_scores_score    ON agent_trust_scores(trust_score);
CREATE INDEX IF NOT EXISTS idx_trust_scores_spoof    ON agent_trust_scores(spoof_detection_flag) WHERE spoof_detection_flag = TRUE;

COMMENT ON TABLE agent_trust_scores IS 'Real-time trust scoring per agent for Phase 6 policy integration';

-- ============================================================
-- 4. MISSING TABLES: anomaly_predictions
-- Predictive intelligence output (Phase 10)
-- ============================================================
CREATE TABLE IF NOT EXISTS anomaly_predictions (
    id                  BIGSERIAL PRIMARY KEY,
    device_id           TEXT NOT NULL,
    site_id             TEXT DEFAULT 'global',
    risk_score          NUMERIC(5,2) NOT NULL DEFAULT 0.0, -- 0.0 to 100.0
    predicted_failure   TEXT NOT NULL, -- 'cpu_degradation','memory_leak','disk_growth','crash_pattern','service_instability'
    confidence          NUMERIC(5,2) NOT NULL DEFAULT 0.0,
    recommended_action  TEXT,
    evidence_window_hrs INTEGER DEFAULT 24, -- hours of data used
    prediction_horizon  INTEGER DEFAULT 4,  -- predicted hours until failure
    model_version       TEXT DEFAULT '1.0',
    feature_snapshot    JSONB DEFAULT '{}',
    status              TEXT DEFAULT 'ACTIVE', -- ACTIVE, ACKNOWLEDGED, RESOLVED, EXPIRED
    predicted_at        TIMESTAMP NOT NULL DEFAULT NOW(),
    resolved_at         TIMESTAMP,
    acknowledged_by     TEXT,
    created_at          TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_anomaly_device    ON anomaly_predictions(device_id);
CREATE INDEX IF NOT EXISTS idx_anomaly_site      ON anomaly_predictions(site_id);
CREATE INDEX IF NOT EXISTS idx_anomaly_risk      ON anomaly_predictions(risk_score DESC);
CREATE INDEX IF NOT EXISTS idx_anomaly_status    ON anomaly_predictions(status);
CREATE INDEX IF NOT EXISTS idx_anomaly_predicted ON anomaly_predictions(predicted_at DESC);
CREATE INDEX IF NOT EXISTS idx_anomaly_active    ON anomaly_predictions(status, risk_score DESC) WHERE status = 'ACTIVE';

COMMENT ON TABLE anomaly_predictions IS 'Predictive failure model output per device (Phase 10)';

-- ============================================================
-- 5. HARDENING: Add missing indexes on critical tables
-- ============================================================

-- approval_queue: index on status for PENDING queries
CREATE INDEX IF NOT EXISTS idx_approval_queue_status ON approval_queue(status);
CREATE INDEX IF NOT EXISTS idx_approval_queue_incident ON approval_queue(incident_id);

-- processed_messages: index for fast idempotency check
CREATE INDEX IF NOT EXISTS idx_processed_messages_id      ON processed_messages(message_id);
CREATE INDEX IF NOT EXISTS idx_processed_messages_subject ON processed_messages(subject);

-- dlq_hybrid: index for PENDING retry worker
CREATE INDEX IF NOT EXISTS idx_dlq_status_retry ON dlq_hybrid(status, retry_count) WHERE status = 'PENDING';

-- rollback_logs: index by incident
CREATE INDEX IF NOT EXISTS idx_rollback_logs_incident ON rollback_logs(incident_id);

-- verification_logs: index by incident
CREATE INDEX IF NOT EXISTS idx_verification_logs_incident ON verification_logs(incident_id);

-- fleet_incidents: composite index for common queries
CREATE INDEX IF NOT EXISTS idx_fleet_incidents_status_created ON fleet_incidents(status, created_at DESC);

-- incident_events: index for tracing
CREATE INDEX IF NOT EXISTS idx_incident_events_incident ON incident_events(incident_id);
CREATE INDEX IF NOT EXISTS idx_incident_events_type     ON incident_events(event_type);

-- ============================================================
-- 6. HARDENING: Materialized view — active incident summary
-- Refreshed periodically for dashboard performance
-- ============================================================
CREATE MATERIALIZED VIEW IF NOT EXISTS mv_incident_summary AS
SELECT
    fi.site_id,
    fi.status,
    COUNT(*) AS count,
    MIN(fi.created_at) AS oldest,
    MAX(fi.created_at) AS newest,
    AVG(EXTRACT(EPOCH FROM (COALESCE(fi.resolved_at, NOW()) - fi.created_at))/60)::NUMERIC(10,2) AS avg_resolution_min
FROM fleet_incidents fi
GROUP BY fi.site_id, fi.status
WITH DATA;

CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_incident_summary ON mv_incident_summary(site_id, status);

COMMENT ON MATERIALIZED VIEW mv_incident_summary IS 'Pre-aggregated incident summary per site/status. REFRESH MATERIALIZED VIEW CONCURRENTLY mv_incident_summary;';

-- ============================================================
-- 7. HARDENING: Materialized view — DLQ depth per site
-- ============================================================
CREATE MATERIALIZED VIEW IF NOT EXISTS mv_dlq_depth AS
SELECT
    COALESCE((payload->>'site_id')::text, 'global') AS site_id,
    status,
    COUNT(*) AS depth,
    MAX(created_at) AS latest_entry
FROM dlq_hybrid
GROUP BY COALESCE((payload->>'site_id')::text, 'global'), status
WITH DATA;

CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_dlq_depth ON mv_dlq_depth(site_id, status);

COMMENT ON MATERIALIZED VIEW mv_dlq_depth IS 'DLQ depth per site for observability. Refresh every 30s.';

-- ============================================================
-- 8. HARDENING: Retention policy helper view
-- Identifies old partitions eligible for archival
-- ============================================================
CREATE OR REPLACE VIEW v_telemetry_retention_audit AS
SELECT
    schemaname,
    tablename,
    pg_size_pretty(pg_total_relation_size(schemaname||'.'||tablename)) AS partition_size,
    CASE
        WHEN tablename ~ 'y(\d{4})m(\d{2})' THEN
            to_date(
                substring(tablename from 'y(\d{4})') || '-' ||
                substring(tablename from 'm(\d{2})') || '-01',
                'YYYY-MM-DD'
            )
        ELSE NULL
    END AS partition_month,
    CASE
        WHEN to_date(
            substring(tablename from 'y(\d{4})') || '-' ||
            substring(tablename from 'm(\d{2})') || '-01',
            'YYYY-MM-DD'
        ) < NOW() - INTERVAL '3 months'
        THEN 'ELIGIBLE_FOR_ARCHIVE'
        ELSE 'RETAIN'
    END AS retention_status
FROM pg_tables
WHERE schemaname = 'public' AND tablename LIKE 'telemetry_logs_y%'
ORDER BY partition_month DESC;

COMMENT ON VIEW v_telemetry_retention_audit IS 'Identifies telemetry partitions older than 3 months for archival';

-- ============================================================
-- 9. HARDENING: Event sourcing compatibility
-- Add trace_id and causal_chain columns to key tables
-- ============================================================
ALTER TABLE incident_events
    ADD COLUMN IF NOT EXISTS trace_id      TEXT,
    ADD COLUMN IF NOT EXISTS causal_chain  TEXT[],
    ADD COLUMN IF NOT EXISTS site_id       TEXT DEFAULT 'global';

ALTER TABLE approval_events
    ADD COLUMN IF NOT EXISTS trace_id TEXT,
    ADD COLUMN IF NOT EXISTS site_id  TEXT DEFAULT 'global';

ALTER TABLE rollback_events
    ADD COLUMN IF NOT EXISTS trace_id TEXT,
    ADD COLUMN IF NOT EXISTS site_id  TEXT DEFAULT 'global';

ALTER TABLE verification_events
    ADD COLUMN IF NOT EXISTS trace_id TEXT,
    ADD COLUMN IF NOT EXISTS site_id  TEXT DEFAULT 'global';

-- Indexes for trace correlation
CREATE INDEX IF NOT EXISTS idx_incident_events_trace ON incident_events(trace_id) WHERE trace_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_approval_events_trace ON approval_events(trace_id) WHERE trace_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_rollback_events_trace ON rollback_events(trace_id) WHERE trace_id IS NOT NULL;

-- ============================================================
-- 10. HARDENING: DLQ — add site_id column for partitioned routing
-- ============================================================
ALTER TABLE dlq_hybrid
    ADD COLUMN IF NOT EXISTS site_id   TEXT DEFAULT 'global',
    ADD COLUMN IF NOT EXISTS event_id  TEXT,
    ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_dlq_site ON dlq_hybrid(site_id);

-- ============================================================
-- 11. VALIDATION: Verify orphan state consistency
-- fleet_incidents that are WAITING_APPROVAL without approval queue entry
-- ============================================================
CREATE OR REPLACE VIEW v_orphan_waiting_approvals AS
SELECT fi.incident_id, fi.status, fi.created_at
FROM fleet_incidents fi
WHERE fi.status = 'WAITING_APPROVAL'
  AND NOT EXISTS (
      SELECT 1 FROM approval_queue aq
      WHERE aq.incident_id = fi.incident_id
        AND aq.status = 'PENDING'
  );

COMMENT ON VIEW v_orphan_waiting_approvals IS 'Incidents stuck in WAITING_APPROVAL without matching pending approval';

-- ============================================================
-- 12. BOOTSTRAP: Seed agent_trust_scores for known agents
-- ============================================================
INSERT INTO agent_trust_scores (agent_name, site_id, trust_score, notes)
VALUES
    ('PC-MKT-NUC',   'idm',            95.0, 'Auto-seeded from fleet'),
    ('auditor_probe', 'global',         100.0, 'Internal probe - always trusted'),
    ('NOC-Agent-01',  'global',         90.0, 'Default NOC agent')
ON CONFLICT (agent_name) DO NOTHING;

COMMIT;

-- ============================================================
-- POST-MIGRATION VERIFICATION
-- ============================================================
DO $$
DECLARE
    v_retry        INTEGER;
    v_trace        INTEGER;
    v_trust        INTEGER;
    v_anomaly      INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_retry   FROM information_schema.tables WHERE table_name = 'retry_history';
    SELECT COUNT(*) INTO v_trace   FROM information_schema.tables WHERE table_name = 'trace_integrity_reports';
    SELECT COUNT(*) INTO v_trust   FROM information_schema.tables WHERE table_name = 'agent_trust_scores';
    SELECT COUNT(*) INTO v_anomaly FROM information_schema.tables WHERE table_name = 'anomaly_predictions';

    RAISE NOTICE '=== PHASE 3 MIGRATION VERIFICATION ===';
    RAISE NOTICE 'retry_history:           %', CASE WHEN v_retry   = 1 THEN 'PASS' ELSE 'FAIL' END;
    RAISE NOTICE 'trace_integrity_reports: %', CASE WHEN v_trace   = 1 THEN 'PASS' ELSE 'FAIL' END;
    RAISE NOTICE 'agent_trust_scores:      %', CASE WHEN v_trust   = 1 THEN 'PASS' ELSE 'FAIL' END;
    RAISE NOTICE 'anomaly_predictions:     %', CASE WHEN v_anomaly = 1 THEN 'PASS' ELSE 'FAIL' END;
    RAISE NOTICE '=======================================';
END $$;
